begin;
select no_plan();
select has_table('public','profiles','profiles exists');
select has_table('public','projects','projects exists');
select has_table('public','interests','interests exists');
select has_table('public','messages','messages exists');
select has_table('public','content_items','content exists');
select policies_are('public','profiles',array['profiles_self','profiles_update_self'],'profiles policies are explicit');
select policies_are('public','projects',array['projects_read','projects_insert','projects_update'],'project policies are explicit');
select policies_are('public','messages',array['messages_read','messages_insert'],'message policies are explicit');
select function_returns('public','consume_project_view',array['uuid'],'record','quota function exists');
select function_returns('public','accept_project_invitation',array['text'],'uuid','invite function exists');
select has_table('public','platform_invitations','platform invitations exist');
select has_table('public','plan_versions','versioned plans exist');
select has_table('public','upload_sessions','quarantine upload sessions exist');
select has_table('public','file_assets','clean file registry exists');
select has_table('public','file_scan_attempts','scan attempts exist');
select has_table('public','domain_events','domain events exist');
select has_table('public','content_revisions','content revision history exists');
select has_column('public','profiles','account_status','account lifecycle is installed');
select has_column('public','profiles','terms_accepted_at','terms acceptance is recorded');
select has_column('public','profiles','privacy_accepted_at','privacy acceptance is recorded');
select has_column('public','projects','revision','project optimistic concurrency is installed');
select has_column('public','entitlements','plan_version_id','entitlements pin plan versions');
select has_column('public','messages','client_nonce','message idempotency is installed');
select has_column('public','deletion_requests','phase','deletion workflow is installed');
select has_function('public','hook_require_platform_invitation',array['jsonb'],'invite-only auth hook exists');
select has_function('public','is_active_account',array['uuid'],'active-account guard exists');
select has_function('public','update_project',array['uuid','integer','jsonb'],'versioned project update exists');
select has_function('public','transition_meeting',array['uuid','text'],'meeting transition exists');
select has_function('public','request_account_deletion',array['text'],'deletion request exists');
select has_function('public','complete_account_deletion',array['uuid'],'deletion completion exists');
select has_function('public','claim_background_jobs',array['text','integer','integer'],'worker claim function exists');
select has_function('public','claim_email_jobs',array['integer'],'atomic email claim exists');
select hasnt_function('public','claim_scan_jobs',array['integer'],'obsolete table-backed scan claim is absent');
select policies_are('public','upload_sessions',array['upload_sessions_self'],'upload sessions are private');
select policies_are('public','file_assets',array['file_assets_member'],'clean files are membership scoped');
select policies_are('public','platform_invitations',array['platform_invites_admin'],'platform invitations are restricted');
select * from finish();
rollback;
