import type { Audience, ContentItem, Locale } from "./types";

export const roles: Array<{ slug: Audience; title: Record<Locale, string>; summary: Record<Locale, string> }> = [
  { slug: "founder", title: { en: "Founders", ml: "സ്ഥാപകർ" }, summary: { en: "Find guidance, collaborators, capital and a clearer next step.", ml: "മാർഗനിർദേശം, സഹപ്രവർത്തകർ, മൂലധനം, അടുത്ത ചുവടുവയ്പ്പ് എന്നിവ കണ്ടെത്തുക." } },
  { slug: "investor", title: { en: "Investors", ml: "നിക്ഷേപകർ" }, summary: { en: "Meet credible ventures and invest with local context.", ml: "വിശ്വസനീയ സംരംഭങ്ങളെ കണ്ടെത്തി പ്രാദേശിക ധാരണയോടെ നിക്ഷേപിക്കുക." } },
  { slug: "mentor", title: { en: "Mentors", ml: "മാർഗദർശകർ" }, summary: { en: "Turn experience into practical, timely founder support.", ml: "അനുഭവത്തെ പ്രായോഗികവും സമയോചിതവുമായ പിന്തുണയാക്കുക." } },
  { slug: "institution", title: { en: "Institutions", ml: "സ്ഥാപനങ്ങൾ" }, summary: { en: "Connect research, talent and infrastructure to real ventures.", ml: "ഗവേഷണം, പ്രതിഭ, അടിസ്ഥാനസൗകര്യങ്ങൾ എന്നിവ സംരംഭങ്ങളുമായി ബന്ധിപ്പിക്കുക." } },
  { slug: "partner", title: { en: "Partners", ml: "പങ്കാളികൾ" }, summary: { en: "Build programs and pathways with shared public value.", ml: "പൊതുമൂല്യമുള്ള പരിപാടികളും മാർഗങ്ങളും ഒരുമിച്ച് സൃഷ്ടിക്കുക." } }
];

export const content: ContentItem[] = [
  { slug: "first-roots-founder-circle", kind: "program", title: { en: "First Roots Founder Circle", ml: "ഫസ്റ്റ് റൂട്ട്സ് ഫൗണ്ടർ സർക്കിൾ" }, summary: { en: "A six-week peer circle for early founders moving from insight to a tested proposition.", ml: "ആശയത്തിൽ നിന്ന് പരീക്ഷിച്ച മൂല്യനിർദ്ദേശത്തിലേക്ക് നീങ്ങുന്ന ആദ്യഘട്ട സ്ഥാപകർക്കുള്ള ആറാഴ്ചത്തെ കൂട്ടായ്മ." }, body: { en: "Small cohorts meet practitioners, test assumptions and leave with a focused ninety-day plan. Designed for founders who value honest feedback over theatre.", ml: "ചെറിയ ഗ്രൂപ്പുകൾ വിദഗ്ധരെ കാണുകയും ധാരണകൾ പരീക്ഷിക്കുകയും വ്യക്തമായ തൊണ്ണൂറ് ദിവസത്തെ പദ്ധതിയോടെ മുന്നോട്ട് പോകുകയും ചെയ്യും." }, category: { en: "Founder development", ml: "സ്ഥാപക വികസനം" }, audience: ["founder", "mentor"], location: { en: "Kochi + online", ml: "കൊച്ചി + ഓൺലൈൻ" }, featured: true },
  { slug: "patient-capital-clinic", kind: "opportunity", title: { en: "Patient Capital Clinic", ml: "പേഷ്യന്റ് ക്യാപിറ്റൽ ക്ലിനിക്" }, summary: { en: "Office hours that help impact-led ventures understand grants, social capital and aligned investment.", ml: "ഗ്രാന്റുകൾ, സാമൂഹിക മൂലധനം, യോജിച്ച നിക്ഷേപം എന്നിവ മനസ്സിലാക്കാൻ സംരംഭങ്ങളെ സഹായിക്കുന്ന ഓഫീസ് അവേഴ്സ്." }, body: { en: "Bring your model, milestones and questions. Independent advisors help map the most appropriate capital path without promising funding.", ml: "നിങ്ങളുടെ മാതൃകയും ലക്ഷ്യങ്ങളും ചോദ്യങ്ങളും കൊണ്ടുവരിക. അനുയോജ്യമായ മൂലധന മാർഗം കണ്ടെത്താൻ സ്വതന്ത്ര ഉപദേഷ്ടാക്കൾ സഹായിക്കും." }, category: { en: "Funding readiness", ml: "ധനസഹായ സന്നദ്ധത" }, audience: ["founder", "investor", "partner"], location: { en: "Online", ml: "ഓൺലൈൻ" }, featured: true },
  { slug: "kerala-builders-assembly", kind: "event", date: "2027-01-23", title: { en: "Kerala Builders Assembly", ml: "കേരള ബിൽഡേഴ്സ് അസംബ്ലി" }, summary: { en: "A working gathering for founders, investors, institutions and ecosystem stewards.", ml: "സ്ഥാപകർ, നിക്ഷേപകർ, സ്ഥാപനങ്ങൾ, ആവാസവ്യവസ്ഥാ പ്രവർത്തകർ എന്നിവർക്കുള്ള പ്രവർത്തന സംഗമം." }, body: { en: "A day of small rooms, useful introductions and public problem-solving—not a parade of panels.", ml: "ചെറിയ ചർച്ചകൾ, ഉപകാരപ്രദമായ പരിചയപ്പെടുത്തലുകൾ, പൊതുപ്രശ്ന പരിഹാരം എന്നിവയുടെ ദിവസം." }, category: { en: "Community gathering", ml: "സമൂഹ സംഗമം" }, audience: ["founder", "investor", "mentor", "institution", "partner"], location: { en: "Thiruvananthapuram", ml: "തിരുവനന്തപുരം" }, featured: true },
  { slug: "beyond-the-pitch", kind: "story", date: "2026-09-14", title: { en: "Beyond the pitch: building for trust", ml: "പിച്ചിനപ്പുറം: വിശ്വാസത്തിനായി നിർമ്മിക്കുക" }, summary: { en: "Why durable ecosystems are built through repeated, useful exchanges—not one-off showcases.", ml: "ഒറ്റത്തവണ പ്രദർശനങ്ങളിലൂടെയല്ല, ആവർത്തിച്ചുള്ള ഉപകാരപ്രദമായ കൈമാറ്റങ്ങളിലൂടെയാണ് സ്ഥായിയായ ആവാസവ്യവസ്ഥകൾ വളരുന്നത്." }, body: { en: "Trust compounds when people show their work, share context and follow through. Kerala's next chapter can be defined by the quality of those connections.", ml: "പ്രവർത്തനം തുറന്ന് കാണിക്കുകയും പശ്ചാത്തലം പങ്കിടുകയും വാഗ്ദാനം പാലിക്കുകയും ചെയ്യുമ്പോൾ വിശ്വാസം വളരുന്നു." }, category: { en: "Field note", ml: "ഫീൽഡ് നോട്ട്" }, audience: ["founder", "investor", "mentor"] },
  { slug: "campus-to-company", kind: "program", title: { en: "Campus to Company", ml: "ക്യാമ്പസിൽ നിന്ന് കമ്പനിയിലേക്ക്" }, summary: { en: "A practical bridge from student project to responsible venture.", ml: "വിദ്യാർത്ഥി പ്രോജക്റ്റിൽ നിന്ന് ഉത്തരവാദിത്ത സംരംഭത്തിലേക്കുള്ള പ്രായോഗിക പാലം." }, body: { en: "Institutions nominate teams for customer discovery, mentor reviews and incorporation readiness.", ml: "ഉപഭോക്തൃ പഠനം, മാർഗദർശക അവലോകനം, കമ്പനി രൂപീകരണ സന്നദ്ധത എന്നിവയ്ക്കായി സ്ഥാപനങ്ങൾ ടീമുകളെ നാമനിർദേശം ചെയ്യുന്നു." }, category: { en: "Student entrepreneurship", ml: "വിദ്യാർത്ഥി സംരംഭകത്വം" }, audience: ["founder", "institution", "mentor"], location: { en: "Across Kerala", ml: "കേരളത്തിലുടനീളം" } }
];

export function findContent(slug: string) { return content.find((item) => item.slug === slug); }
export function formatDate(date: string, locale: Locale) { return new Intl.DateTimeFormat(locale === "ml" ? "ml-IN" : "en-IN", { day: "numeric", month: "long", year: "numeric", timeZone: "Asia/Kolkata" }).format(new Date(`${date}T00:00:00+05:30`)); }
