project_id = "thalir"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.hook.before_user_created]
enabled = true
uri = "pg-functions://postgres/public/hook_require_platform_invitation"

[storage]
enabled = true
file_size_limit = "20MiB"

[realtime]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"
