"use server";
import { createHash,randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { createAdminClientOrThrow } from "@/lib/supabase/server";
import { getViewer } from "@/lib/viewer";
import { getLocale } from "@/lib/i18n";
import { supabaseConfig } from "@/lib/supabase/config";
async function admin(fresh=false){const viewer=await getViewer();if(viewer.profile?.role!=="admin"||viewer.profile.account_status!=="active")throw new Error("FORBIDDEN");const {data:aal}=await viewer.client!.auth.mfa.getAuthenticatorAssuranceLevel();if(supabaseConfig.adminMfaRequired&&aal?.currentLevel!=="aal2")throw new Error("MFA_REQUIRED");if(fresh&&aal?.currentLevel!=="aal2")throw new Error("FRESH_AUTH_REQUIRED");return {client:createAdminClientOrThrow(),actor:viewer.profile.id}}
export async function assignPlan(form:FormData){const locale=getLocale(String(form.get("locale")));const {client,actor}=await admin(true);const reason=String(form.get("reason")??"").trim();if(reason.length<4)throw new Error("REASON_REQUIRED");const planId=String(form.get("planId")),userId=String(form.get("userId"));const {data:version}=await client.from("plan_versions").select("id").eq("plan_id",planId).order("version",{ascending:false}).limit(1).single();await client.from("entitlements").insert({user_id:userId,plan_id:planId,plan_version_id:version?.id,assigned_by:actor,assignment_reason:reason});await client.from("profiles").update({account_status:"active"}).eq("id",userId);revalidatePath(`/${locale}/admin`)}
export async function createPlatformInvitation(form:FormData){const locale=getLocale(String(form.get("locale")));const {client,actor}=await admin(true);const email=String(form.get("email")??"").trim().toLowerCase(),role=String(form.get("role")) as "founder"|"investor"|"admin",tier=String(form.get("investorTier")||"") as "community_backer"|"venture_investor"|"";if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error("VALIDATION_ERROR");const rawToken=randomBytes(32).toString("base64url"),tokenHash=createHash("sha256").update(rawToken).digest("hex"),expiresAt=new Date(Date.now()+supabaseConfig.invitationExpiryHours*3600000).toISOString();await client.from("platform_invitations").update({status:"revoked",revoked_at:new Date().toISOString(),revocation_reason:"Superseded by resend"}).eq("normalized_email",email).eq("status","pending");const {data:invitation,error}=await client.from("platform_invitations").insert({email,role,investor_tier:role==="investor"&&tier?tier:null,initial_plan_id:String(form.get("planId")||"")||null,locale,status:"pending",token_hash:tokenHash,invited_by:actor,expires_at:expiresAt}).select("id").single();if(error||!invitation)throw new Error("INVITATION_CREATE_FAILED");const redirectTo=`${supabaseConfig.redirectOrigin}/auth/callback?next=/${locale}/app`;const {error:deliveryError}=await client.auth.admin.inviteUserByEmail(email,{redirectTo,data:{platform_invitation_id:invitation.id}});await client.from("platform_invitations").update({delivery_status:deliveryError?"failed":"sent",delivery_attempts:1,last_delivered_at:deliveryError?null:new Date().toISOString()}).eq("id",invitation.id);revalidatePath(`/${locale}/admin`)}
export async function revokePlatformInvitation(form:FormData){const locale=getLocale(String(form.get("locale")));const {client}=await admin(true);const reason=String(form.get("reason")??"").trim();if(reason.length<4)throw new Error("REASON_REQUIRED");await client.from("platform_invitations").update({status:"revoked",revoked_at:new Date().toISOString(),revocation_reason:reason}).eq("id",String(form.get("invitationId"))).eq("status","pending");revalidatePath(`/${locale}/admin`)}
export async function publishContent(form:FormData){const locale=getLocale(String(form.get("locale")));const {client,actor}=await admin();const id=String(form.get("id"));await client.from("content_items").update({status:String(form.get("status")) as "published",updated_by:actor,updated_at:new Date().toISOString()}).eq("id",id);revalidatePath(`/${locale}/admin`)}
export async function updateContent(form:FormData){const locale=getLocale(String(form.get("locale")));const {client,actor}=await admin();const id=String(form.get("id"));await client.from("content_items").update({title_en:String(form.get("titleEn")),title_ml:String(form.get("titleMl")),summary_en:String(form.get("summaryEn")),summary_ml:String(form.get("summaryMl")),body_en:String(form.get("bodyEn")),body_ml:String(form.get("bodyMl")),updated_by:actor,updated_at:new Date().toISOString()}).eq("id",id);revalidatePath(`/${locale}/admin`)}
